# Generated by Django 3.2 on 2022-12-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indices', models.CharField(choices=[('n', 'NIFTY'), ('b', 'SENSEX'), ('d', 'DFMGI'), ('a', 'DAX'), ('n', 'BSE500')], max_length=1)),
            ],
        ),
    ]
