# Generated by Django 3.2 on 2022-12-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(choices=[('r', 'RELIANCE'), ('l', 'LICI'), ('i', 'IOC'), ('s', 'SBIN'), ('t', 'TATASTEEL')], max_length=1)),
            ],
        ),
    ]
