# Generated by Django 4.1.4 on 2022-12-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_name", models.CharField(max_length=200)),
                ("profilephoto", models.FileField(upload_to="docs/profile")),
                ("newspost", models.CharField(max_length=200)),
                ("videopost", models.FileField(upload_to="docs/vedio")),
                ("photopost", models.FileField(upload_to="docs/photo")),
                ("comments", models.CharField(max_length=200)),
                ("likes", models.IntegerField()),
                ("postdate", models.CharField(max_length=200)),
            ],
        ),
    ]
