# Generated by Django 4.1.4 on 2022-12-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="postdate",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
