# Generated by Django 3.2 on 2022-12-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_profile_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='postdate',
        ),
    ]
