# Generated by Django 3.2 on 2023-01-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_remove_profile_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
