# Generated by Django 4.1.5 on 2023-01-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(choices=[('r', 'RELIANCE'), ('l', 'LICI'), ('i', 'IOC'), ('s', 'SBIN'), ('t', 'TATASTEEL'), ('y', 'INFY'), ('c', 'TCS'), ('d', 'HDFC'), ('k', 'HDFCBANK'), ('h', 'HINDUNILVR'), ('n', 'ICICIBANK')], max_length=1)),
            ],
        ),
    ]
