# Generated by Django 3.2 on 2023-01-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutual', '0002_delete_mutualmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='patani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(max_length=123478, null=True)),
            ],
        ),
    ]
