# Generated by Django 4.1.4 on 2022-12-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profilemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('about', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
